name: Playwright Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs tests for pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can change to windows-latest if required

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change this to match your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/  # Runs tests inside the 'tests/' folder

      - name: Upload Playwright report
        if: always()  # Always upload reports, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
